In [3]:
from voting_fns import plurality, iterative_plurality, RCR_iterative_plurality
import random
import matplotlib.pyplot as plt
import numpy as np

Iterative Plurality vs Randomized Candidate Removal Iterative Plurality

In [4]:
num_voters = [10, 20, 50]
num_candidates = {10:[3,5,7,10],
                  20:[5,10,15,20],
                  50:[10,20,30,40,50],
                  100:[10,25,50,75,90,100],
                  200:[25,50,100,150,175,200]}

num_simulations = 100

plurality_results = []
RCR_results = []

same_result = []

for n in num_voters:
    for m in num_candidates[n]:
        if m > n:
            continue

        print((n,m))

        max_iter_p = 0
        sum_iter_p = 0

        max_iter_rcr = 0
        sum_iter_rcr = 0

        same = 0
        for i in range(num_simulations):
            if i%25 == 0:
                print("Simulation # ", i)

            
            L = []
            for voter in range(n):
                preference_profile = [*range(m)]
                random.shuffle(preference_profile)
                L.append(preference_profile)
            
            initial_state = [random.randint(0,m-1) for preference_profile in L]

            _, _, tc_p, num_iter_p = iterative_plurality(L, m, from_truth=False, initial_state=initial_state.copy())
            _, _, tc_rcr, num_iter_rcr = RCR_iterative_plurality(L, m, from_truth=False, initial_state=initial_state)

            if tc_p == tc_rcr:
                same += 1


            sum_iter_p += num_iter_p
            sum_iter_rcr += num_iter_rcr

            if num_iter_p > max_iter_p:
                max_iter_p = num_iter_p

            if num_iter_rcr > max_iter_rcr:
                max_iter_rcr = num_iter_rcr
        
        plurality_results.append([n, m, sum_iter_p/num_simulations, max_iter_p])
        RCR_results.append([n, m, sum_iter_rcr/num_simulations, max_iter_rcr])

        same_result.append([n, m, same/num_simulations])



(10, 3)
Simulation #  0
Simulation #  25
Simulation #  50
Simulation #  75
(10, 5)
Simulation #  0
Simulation #  25
Simulation #  50
Simulation #  75
(10, 7)
Simulation #  0
Simulation #  25
Simulation #  50
Simulation #  75
(10, 10)
Simulation #  0
Simulation #  25
Simulation #  50
Simulation #  75
(20, 5)
Simulation #  0
Simulation #  25
Simulation #  50
Simulation #  75
(20, 10)
Simulation #  0
Simulation #  25
Simulation #  50
Simulation #  75
(20, 15)
Simulation #  0
Simulation #  25
Simulation #  50
Simulation #  75
(20, 20)
Simulation #  0
Simulation #  25
Simulation #  50
Simulation #  75
(50, 10)
Simulation #  0
Simulation #  25
Simulation #  50
Simulation #  75
(50, 20)
Simulation #  0
Simulation #  25
Simulation #  50
Simulation #  75
(50, 30)
Simulation #  0
Simulation #  25
Simulation #  50
Simulation #  75
(50, 40)
Simulation #  0
Simulation #  25
Simulation #  50
Simulation #  75
(50, 50)
Simulation #  0
Simulation #  25
Simulation #  50
Simulation #  75


In [5]:
print(plurality_results)
plurality_results = np.asarray(plurality_results)

array([[ 10. ,   3. ,  23.2,  60. ],
       [ 10. ,   5. ,  26.7,  60. ],
       [ 10. ,   7. ,  27.6,  60. ],
       [ 10. ,  10. ,  30.6,  60. ],
       [ 20. ,   5. ,  65.4, 140. ],
       [ 20. ,  10. ,  66.8, 160. ],
       [ 20. ,  15. ,  77.2, 180. ],
       [ 20. ,  20. ,  72.6, 140. ],
       [ 50. ,  10. , 216.5, 550. ],
       [ 50. ,  20. , 245. , 550. ],
       [ 50. ,  30. , 237. , 600. ],
       [ 50. ,  40. , 247.5, 600. ],
       [ 50. ,  50. , 251. , 650. ]])

In [6]:
print(RCR_results)
RCR_results = np.asarray(RCR_results)

array([[ 10. ,   3. ,  15.9,  20. ],
       [ 10. ,   5. ,  27. ,  40. ],
       [ 10. ,   7. ,  27.8,  60. ],
       [ 10. ,  10. ,  30.6,  60. ],
       [ 20. ,   5. ,  60.6,  80. ],
       [ 20. ,  10. ,  67.8, 180. ],
       [ 20. ,  15. ,  77.2, 180. ],
       [ 20. ,  20. ,  72.6, 140. ],
       [ 50. ,  10. , 237.5, 450. ],
       [ 50. ,  20. , 245. , 550. ],
       [ 50. ,  30. , 237. , 600. ],
       [ 50. ,  40. , 247.5, 600. ],
       [ 50. ,  50. , 251. , 650. ]])

In [7]:
print(same_result)
same_result = np.asarray(same_result)

array([[10.  ,  3.  ,  0.85],
       [10.  ,  5.  ,  0.77],
       [10.  ,  7.  ,  0.95],
       [10.  , 10.  ,  1.  ],
       [20.  ,  5.  ,  0.61],
       [20.  , 10.  ,  0.91],
       [20.  , 15.  ,  1.  ],
       [20.  , 20.  ,  1.  ],
       [50.  , 10.  ,  0.58],
       [50.  , 20.  ,  0.99],
       [50.  , 30.  ,  1.  ],
       [50.  , 40.  ,  1.  ],
       [50.  , 50.  ,  1.  ]])